"""
Rule-based tariff estimation for country pairs not already covered by
data/processed/estimated_tariffs.csv.

That file only has a tariff estimate for the 171 (source, target) pairs that
already trade in cleaned_edges.csv. Inspecting it shows the rate is really
generated by a small priority-ordered rule set, not true pairwise data:

    1. a specific bilateral FTA pair (e.g. USA <-> Canada, 0%)
    2. both countries in the EU/EEA/UK/CH free-trade zone (0%)
    3. a special flat rate for a handful of importers regardless of partner
       (Hong Kong as a free port, Singapore's low-tariff FTA network default)
    4. otherwise, that importer's general default rate

This module reimplements that same rule set so it can be applied to *any*
importer/candidate-supplier pair - e.g. for rerouting analysis, where the
candidate replacement supplier may not have an existing trade relationship
with the importer. Like the source file, every estimate here is a rough
placeholder, not a real tariff schedule lookup.
"""

from pathlib import Path

import pandas as pd

# Countries in our dataset that are members of the EU/EEA/UK/CH free-trade zone.
EU_EEA_UK_CH_ZONE = {
    "Austria", "Belgium", "Bulgaria", "Croatia", "Czechia", "Denmark",
    "Estonia", "Finland", "France", "Germany", "Hungary", "Iceland",
    "Ireland", "Italy", "Lithuania", "Luxembourg", "Netherlands", "Poland",
    "Portugal", "Romania", "Slovakia", "Spain", "Sweden", "Switzerland",
    "United Kingdom",
}

# Flat rate charged by these importers regardless of partner (evidenced in
# estimated_tariffs.csv: Hong Kong as a free port, Singapore's FTA network).
SPECIAL_IMPORTER_RATES = {
    "China, Hong Kong SAR": (0.0, "hk_free_port"),
    "Singapore": (0.005, "sg_low_tariff_fta_network"),
}

# Known bilateral FTA pairs that override the general default (0% either way).
BILATERAL_FTA_PAIRS = {
    frozenset({"USA", "Canada"}): "bilateral_fta_bloc",
}

# Fallback for an importer never observed in estimated_tariffs.csv.
FALLBACK_DEFAULT_RATE = 0.02
FALLBACK_DEFAULT_METHODOLOGY = "importer_default_unclassified"


def derive_importer_default_rates(tariffs: pd.DataFrame) -> dict[str, tuple[float, str]]:
    """Derive each importer's general default rate from a tariff table.

    Expects columns source, target, estimated_tariff_pct, tariff_methodology
    (as found in estimated_tariffs.csv, or cleaned_edges.csv once merged).
    Excludes rows explained by a more specific rule (zone or bilateral FTA),
    then takes the most common remaining rate/methodology per importer -
    e.g. Egypt -> (0.06, "importer_default_lower_middle_income").
    """

    default_rows = tariffs[~tariffs["tariff_methodology"].isin(
        ["eu_eea_uk_ch_zone", "bilateral_fta_bloc"]
    )]

    rates = {}
    for importer, group in default_rows.groupby("source"):
        rate = group["estimated_tariff_pct"].mode()[0]
        methodology = group["tariff_methodology"].mode()[0]
        rates[importer] = (float(rate), methodology)

    return rates


def load_importer_default_rates(tariffs_path: Path | str) -> dict[str, tuple[float, str]]:
    """Same as derive_importer_default_rates, reading the tariff table from a CSV path."""

    return derive_importer_default_rates(pd.read_csv(tariffs_path))


def estimate_tariff_pct(
    importer: str, partner: str, importer_default_rates: dict[str, tuple[float, str]]
) -> dict:
    """Estimate a tariff rate for an (importer, partner) pair using the rule
    priority: bilateral FTA pair > shared EU/EEA/UK/CH zone > special flat-rate
    importer > importer's general default.

    Args:
        importer: the country recorded as importing/reporting the trade.
        partner: the country recorded as supplying/exporting the good.
        importer_default_rates: output of load_importer_default_rates().

    Returns:
        {"estimated_tariff_pct": float, "tariff_methodology": str, "is_placeholder_estimate": True}
    """

    if frozenset({importer, partner}) in BILATERAL_FTA_PAIRS:
        return {
            "estimated_tariff_pct": 0.0,
            "tariff_methodology": BILATERAL_FTA_PAIRS[frozenset({importer, partner})],
            "is_placeholder_estimate": True,
        }

    if importer in EU_EEA_UK_CH_ZONE and partner in EU_EEA_UK_CH_ZONE:
        return {
            "estimated_tariff_pct": 0.0,
            "tariff_methodology": "eu_eea_uk_ch_zone",
            "is_placeholder_estimate": True,
        }

    if importer in SPECIAL_IMPORTER_RATES:
        rate, methodology = SPECIAL_IMPORTER_RATES[importer]
        return {
            "estimated_tariff_pct": rate,
            "tariff_methodology": methodology,
            "is_placeholder_estimate": True,
        }

    rate, methodology = importer_default_rates.get(
        importer, (FALLBACK_DEFAULT_RATE, FALLBACK_DEFAULT_METHODOLOGY)
    )
    return {
        "estimated_tariff_pct": rate,
        "tariff_methodology": methodology,
        "is_placeholder_estimate": True,
    }
